name: Test repo
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          ref: ${{github.ref}}
      - name: Create something
        run: touch puikula.txt
      - name: Commit Changes
        run: |
          git config --global user.name 'repenaattori'
          git config --global user.email 'reimarii@oamk.fi'
          git add .
          git commit -m 'Build added'
          git push
